### ISSUE TITLE
Systematics for legacy 2017

### ISSUE THREAD

**Issue by simonepigazzini** [cms-analysis/flashgg#1222] opened 2020-07-13 08:22 UTC
We should prepare the systematic workflow to handle the legacy samples, starting from 2017. 
Probably it makes sense to start with with diphoton systematics where probably it still makes sense to have a separate file for legacy 2017 (that might eventually be merged with the one we are using now once the usage of ReReco17 fades out).

The main points on the list is of course to get the EGM energy correction right and the GTs. 

@rchatter

**Comment by simonepigazzini** [comment] 2020-07-13 08:29
https://github.com/cms-analysis/flashgg/blob/45a6a51f166d4a4746c6cea863e897011f342e5f/MetaData/data/MetaConditions/Era2017_legacy_v1.json#L4

Mc is fine, the recommended one for data is v28 (https://twiki.cern.ch/twiki/bin/view/CMS/PdmVRun2LegacyAnalysisSummaryTable). I think v17 is still fine for microAOD production, we will update to v28 with any coming PR related to this.

@alesauva

**Comment by simonepigazzini** [comment] 2020-08-12 07:57
@rchatter can you setup the scale and smearing for lagacy 2017? I would go again with a separate diphotonSystematics config file that is then specified in the meta conditions.

@threiten  @edjtscott I think we need at least scale and smearings to go ahead with the differential pho ID corrections

**Comment by rchatter** [comment] 2020-08-12 15:41
Hi Simone,

Yes I have everything to push this diphoSyst file(privately provided to a few people already) as you asked. Just want to explicitly test it on the DoubleEG Legacy17 dataset before committing[unfortunately there seems to have been an issue in the MuAOD production].
The reason for this extra caution is that nominally for all of CMS we changed the scale correction file format and the corresponding EGamma scale correction class to deal with it (This was a long standing request from multiple people, to migrate the scale correction to DB and this change in format is the first step). All future Legacy scale correction files will be in the new format. However for continuity in HGG I also produced the file in the old format[like we currently have for the 3 years]. Hence also checking that it works fine with the dipho data.

Rajdeep

**Comment by simonepigazzini** [comment] 2020-08-12 21:19
Thomas is going to produce tnp ntuple for the pho ID correction
training, I guess we can use those to have the validation (he will share
them with you in case you want to take a look), so I think it is best if
you can make a PR with the changes needed to run with the old format and
we will migrate everything together once the new format is available for
all years. What do you think?

**Comment by edjtscott** [comment] 2020-08-27 17:34
I think we can almost close this issue @simonepigazzini since @rchatter made the PR and it has been merged. However I notice that [this line](https://github.com/cms-analysis/flashgg/blob/dev_legacy_runII/MetaData/data/MetaConditions/Era2017_legacy_v1.json#L87) in the legacy meta conditions file was not changed - it should be updated right? If so that should be fixed first.

**Comment by rchatter** [comment] 2020-08-27 17:42
Nice catch! Completely forgot to update the metaconditions.
Shall be cross-check if the updates needed for UL17 JEC/JER and also update the B-tagging SFs on top of this and then close the PR?

**Comment by edjtscott** [comment] 2020-08-27 17:43
Yes good idea, we can keep this open until those are confirmed / sorted

**Comment by rchatter** [comment] 2020-11-26 20:01
I believe we can close this now right?

**Comment by youyingli** [comment] 2020-11-27 02:31
Yes, all systematics for UL2017 have been confirmed!

**Closed as completed by youyingli** 2020-11-27 02:31 UTC
